### ISSUE TITLE
压缩浮点数时为什么用5个bit位存储前导零

### ISSUE THREAD

**Issue by InfiniteNightmare** [MrBean818/gorilla-paper-encode#1]
论文说当 block of meaningful bits 不在先前的范围内，用 5 bits 存前导零的数量，6 bits 存 meaningful bits 的数量，最后存 meaningful bits, value 的类型限定为双精度浮点数，总共有 64 位，2 ^ 6 = 64，不应该用 6 bits 来存前导零的数量，为什么用 5 bits？而 meaningful bits 的数量也是用 6 bits。我看论文时理解不了这点，我在 GitHub 上看到了你的实现，就想向你请教一下。

**Comment by MrBean818** [comment]
From ChatGPT
Gorilla Paper 中提到的前导零数量和位数是 5 位，原因是基于优化和压缩的需求：

位数限制：一般来说，数据存储中会有一些特定的限制，比如在 32 位系统中，最多能够表示的位数就是 32 位。而在时间序列的压缩中，往往会利用 "前导零" 来减少存储量。Gorilla Paper 选择 5 位来表示前导零数量，实际上是基于压缩效率与存储效率之间的折中。

常见的变化范围：对于时间戳或者其他大多数时间序列数据，数据之间的变化一般不会超过 32 位整数的范围。所以，理论上，最多也只需要 32 个前导零。这样，最多有 32 个连续的零可以用于编码数值变化。

存储结构的约束：5 位能有效地表示 0 到 31 的前导零数量，而超过这个数量的前导零在实际中并不常见。实际上，时间序列数据中的变动通常不会很大，所以通过限制前导零的数量来优化存储就变得有意义。

高效的压缩：通过使用较小的位数（例如 5 位），Gorilla Paper 能够以较小的代价快速地编码大部分的时间序列数据的前导零，从而提高压缩率，同时避免过度压缩导致的性能问题。
